Update CnRDNAKmet.sh
c/var/lib/slurmd/job27636518/slurm_script: line 13: =: command not found
(ERR): "/ref/Ncrassa_ref" does not exist or is not a Bowtie 2 index
Exiting now ...
Error: could not open /ref/ecoli_refseq.fa
Error: Encountered internal Bowtie 2 exception (#1)
Command: /apps/eb/Bowtie2/2.5.2-GCC-11.3.0/bin/bowtie2-build-s --wrapper basic-0 -f /ref/ecoli_refseq.fa /ref/ecoli_ref
(ERR): "/ref/ecoli_ref" does not exist or is not a Bowtie 2 index
Exiting now ...
/var/lib/slurmd/job27636518/slurm_script: line 53: /bam_files/.bam: No such file or directory
/var/lib/slurmd/job27636518/slurm_script: line 54: /bam_files/_Ecoli.bam: No such file or directory
[E::hts_open_format] Failed to open file "/bam_files/.bam" : No such file or directory
samtools sort: can't open "/bam_files/.bam": No such file or directory
[E::hts_open_format] Failed to open file "/bam_files/_Ecoli.bam" : No such file or directory
samtools sort: can't open "/bam_files/_Ecoli.bam": No such file or directory